import { BarcodeScanningResult, CameraView, useCameraPermissions } from 'expo-camera';
import { router } from 'expo-router';
import { useCallback, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Button, Card, Field, Screen, ui } from '@/components/ui';
import { eventDate } from '@/lib/format';
import { palette } from '@/lib/theme';
import { useAuth } from '@/providers/AuthProvider';

type Match = { code: string; kind: string; ticket_type: string; name: string; state: 'valid' | 'used' | 'unpaid'; event: { name: string; date: string; track: { name: string } }; car?: { label: string }; registration_id?: number; inspection_state?: 'not_started' | 'needs_attention' | 'passed'; checked_in_at?: string | null };

export default function ScannerScreen() {
  const { api } = useAuth(); const [permission, askPermission] = useCameraPermissions(); const [query, setQuery] = useState(''); const [matches, setMatches] = useState<Match[]>([]); const [locked, setLocked] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<{ tone: 'error' | 'success'; text: string } | null>(null);
  const lookup = useCallback(async (value: string) => { if (!value.trim()) return; setBusy(true); setNotice(null); try { const body = await api<{ results: Match[] }>('/staff/tickets/lookup', { method: 'POST', body: JSON.stringify({ query: value }) }); setMatches(body.results); if (!body.results.length) setNotice({ tone: 'error', text: 'No matching ticket found at your track.' }); } catch (e) { setMatches([]); setNotice({ tone: 'error', text: e instanceof Error ? e.message : 'Lookup failed.' }); } finally { setBusy(false); } }, [api]);
  const scanned = ({ data }: BarcodeScanningResult) => { if (locked) return; setLocked(true); setQuery(data); lookup(data); };
  const admit = async (match: Match) => { setBusy(true); setNotice(null); try { const body = await api<{ ticket: Match }>(`/staff/tickets/${encodeURIComponent(match.code)}/check-in`, { method: 'POST' }); setMatches([body.ticket]); setNotice({ tone: 'success', text: `${body.ticket.name} is checked in.` }); } catch (e) { setNotice({ tone: 'error', text: e instanceof Error ? e.message : 'Check-in failed.' }); } finally { setBusy(false); } };
  const next = () => { setLocked(false); setQuery(''); setMatches([]); setNotice(null); };

  return <Screen><View style={styles.heading}><Text style={styles.eyebrow}>GATE MODE</Text><Text style={styles.title}>Ticket scanner</Text><Text style={styles.subtitle}>The camera stays ready. Scan a QR code or search by name, email, or ticket code.</Text></View>
    {!permission?.granted ? <Card><Text style={ui.title}>Camera access</Text><Text style={[ui.body, { marginVertical: 8 }]}>Allow camera access once to scan tickets continuously.</Text><Button title="Allow camera" onPress={askPermission} /></Card> : <View style={styles.cameraWrap}><CameraView style={styles.camera} facing="back" barcodeScannerSettings={{ barcodeTypes: ['qr'] }} onBarcodeScanned={locked ? undefined : scanned} /><View pointerEvents="none" style={styles.frame} /><View style={styles.cameraLabel}><Text style={styles.cameraLabelText}>{locked ? 'Result loaded' : 'Hold QR inside the frame'}</Text></View></View>}
    <View style={styles.search}><Field style={{ flex: 1 }} autoCapitalize="none" placeholder="Name, email, or ticket code" value={query} onChangeText={setQuery} onSubmitEditing={() => { setLocked(true); lookup(query); }} /><View style={{ width: 92 }}><Button title={busy ? 'Wait…' : 'Find'} onPress={() => { setLocked(true); lookup(query); }} disabled={busy || !query.trim()} /></View></View>
    {notice ? <View style={[styles.notice, notice.tone === 'success' ? styles.success : styles.error]}><Text style={[styles.noticeText, notice.tone === 'success' ? styles.successText : styles.errorText]}>{notice.text}</Text></View> : null}
    {matches.map(match => <Card key={`${match.kind}-${match.code}`} style={match.state === 'used' && match.kind !== 'driver' ? styles.usedCard : undefined}><View style={ui.between}><View style={{ flex: 1 }}><Text style={styles.kind}>{match.ticket_type}</Text><Text style={styles.person}>{match.name}</Text></View><View style={[styles.state, match.state === 'valid' || (match.kind === 'driver' && match.state === 'used') ? styles.stateValid : styles.stateStop]}><Text style={[styles.stateText, match.state === 'valid' || (match.kind === 'driver' && match.state === 'used') ? styles.stateValidText : styles.stateStopText]}>{match.kind === 'driver' && match.state === 'used' ? '✓ CHECKED IN' : match.state === 'used' ? 'STOP · USED' : match.state.toUpperCase()}</Text></View></View><View style={styles.details}><Text style={ui.body}>{match.event.name}</Text><Text style={ui.body}>{eventDate(match.event.date)} · {match.event.track.name}</Text>{match.car ? <Text style={ui.body}>{match.car.label}</Text> : null}{match.kind === 'driver' && match.state === 'used' ? <Text style={[ui.body, match.inspection_state === 'passed' && styles.passed]}>{match.inspection_state === 'passed' ? '✓ Inspection passed' : match.inspection_state === 'needs_attention' ? 'Inspection needs attention' : 'Inspection not started'}</Text> : null}</View>{match.state === 'valid' ? <Button title={busy ? 'Checking in…' : 'Check in'} onPress={() => admit(match)} disabled={busy} /> : match.kind === 'driver' && match.registration_id ? <Button title={match.inspection_state === 'passed' ? 'Review inspection' : 'Inspect vehicle'} onPress={() => router.push(`/inspection/${match.registration_id}`)} disabled={busy} /> : null}</Card>)}
    {locked ? <Button tone="secondary" title="Scan next ticket" onPress={next} /> : null}
  </Screen>;
}

const styles = StyleSheet.create({ heading: { paddingVertical: 4 }, eyebrow: { color: palette.orange, fontWeight: '900', letterSpacing: 1.2, fontSize: 11 }, title: { color: palette.ink, fontSize: 28, fontWeight: '900', marginTop: 4 }, subtitle: { color: palette.muted, lineHeight: 20, marginTop: 6 }, cameraWrap: { height: 310, borderRadius: 22, overflow: 'hidden', backgroundColor: '#000' }, camera: { flex: 1 }, frame: { position: 'absolute', width: 205, height: 205, borderWidth: 3, borderColor: 'white', borderRadius: 22, alignSelf: 'center', top: 40 }, cameraLabel: { position: 'absolute', bottom: 15, alignSelf: 'center', backgroundColor: 'rgba(16,24,40,.84)', paddingHorizontal: 13, paddingVertical: 8, borderRadius: 99 }, cameraLabelText: { color: 'white', fontSize: 12, fontWeight: '800' }, search: { flexDirection: 'row', gap: 8 }, notice: { borderRadius: 14, padding: 15 }, success: { backgroundColor: palette.greenSoft }, error: { backgroundColor: palette.redSoft }, noticeText: { fontWeight: '900', fontSize: 15 }, successText: { color: palette.green }, errorText: { color: palette.red }, kind: { color: palette.orange, fontSize: 11, fontWeight: '900', letterSpacing: .8, textTransform: 'uppercase' }, person: { color: palette.ink, fontSize: 21, fontWeight: '900', marginTop: 3 }, state: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 }, stateText: { fontSize: 11, fontWeight: '900' }, stateValid: { backgroundColor: palette.greenSoft }, stateValidText: { color: palette.green }, stateStop: { backgroundColor: palette.red }, stateStopText: { color: 'white' }, details: { borderTopWidth: 1, borderTopColor: palette.line, borderBottomWidth: 1, borderBottomColor: palette.line, paddingVertical: 12, marginVertical: 13, gap: 3 }, usedCard: { borderColor: '#FDA29B', borderWidth: 2 }, passed: { color: palette.green, fontWeight: '800', marginTop: 4 } });
