import { useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Card, Empty, Hero, Loading, Screen, SectionTitle, ui } from '@/components/ui';
import { eventDate, money } from '@/lib/format';
import { palette } from '@/lib/theme';
import type { TrackEvent } from '@/lib/types';
import { useAuth } from '@/providers/AuthProvider';

type Detail = TrackEvent & { registration?: { checked_in_at: string | null; ticket_code: string; car: { label: string } } | null; vendors?: { id: number | null; business_name: string; website?: string; logo_url?: string }[]; registration_count?: number; checked_in_count?: number };
export default function EventDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { account, api } = useAuth(); const [event, setEvent] = useState<Detail | null>(null); const [failed, setFailed] = useState(false);
  useEffect(() => { if (!account || !['user', 'employee'].includes(account.type)) { setFailed(true); return; } const path = account.type === 'employee' ? `/staff/events/${id}` : `/driver/events/${id}`; api<{ event: Detail }>(path).then(body => setEvent(body.event)).catch(() => setFailed(true)); }, [account, api, id]);
  if (!event && !failed) return <Loading />; if (!event) return <Screen><Empty title="Event unavailable" detail="This event is not available to your account." /></Screen>;
  return <Screen><Hero eyebrow={event.type === 'private' ? 'Private rental' : event.track.name} title={event.name} subtitle={`${eventDate(event.date)} · ${event.track.location}`} /><Card><Text style={ui.title}>Event details</Text><View style={styles.line}><Text style={ui.body}>Driver admission</Text><Text style={styles.value}>{money(event.prices.driver)}</Text></View><View style={styles.line}><Text style={ui.body}>Capacity</Text><Text style={styles.value}>{event.availability?.driver?.unlimited ? 'Open' : `${event.availability?.driver?.remaining ?? 0} left`}</Text></View>{event.registration_count !== undefined ? <><View style={styles.line}><Text style={ui.body}>Drivers registered</Text><Text style={styles.value}>{event.registration_count}</Text></View><View style={styles.line}><Text style={ui.body}>Checked in</Text><Text style={styles.value}>{event.checked_in_count}</Text></View></> : null}{event.registration ? <View style={styles.booked}><Text style={styles.bookedTitle}>You’re registered</Text><Text style={styles.bookedText}>{event.registration.car.label}{event.registration.checked_in_at ? ' · Checked in' : ''}</Text></View> : null}</Card>{account?.type === 'user' ? <><SectionTitle title="Vendors onsite" />{event.vendors?.length ? <View style={styles.vendorGrid}>{event.vendors.map((vendor, index) => <Card key={`${vendor.id}-${index}`} style={styles.vendor}><View style={styles.vendorLogo}><Text style={styles.vendorInitial}>{vendor.business_name.slice(0, 2).toUpperCase()}</Text></View><Text numberOfLines={2} style={styles.vendorName}>{vendor.business_name}</Text></Card>)}</View> : <Empty title="No vendors announced" detail="Paid event vendors will appear here." />}</> : null}</Screen>;
}
const styles = StyleSheet.create({ line: { flexDirection: 'row', justifyContent: 'space-between', paddingTop: 12, marginTop: 12, borderTopWidth: 1, borderTopColor: palette.line }, value: { color: palette.ink, fontWeight: '900' }, booked: { backgroundColor: palette.greenSoft, borderRadius: 13, padding: 13, marginTop: 16 }, bookedTitle: { color: palette.green, fontWeight: '900' }, bookedText: { color: palette.green, marginTop: 3 }, vendorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, vendor: { width: '48%', alignItems: 'center' }, vendorLogo: { width: 76, height: 76, borderRadius: 20, backgroundColor: palette.navy, alignItems: 'center', justifyContent: 'center', marginBottom: 10 }, vendorInitial: { color: 'white', fontWeight: '900', fontSize: 21 }, vendorName: { color: palette.ink, textAlign: 'center', fontWeight: '800' } });
